minimumReleaseAge: 7200

minimumReleaseAgeExclude:
  - h3@1.15.9
  - serialize-javascript@7.0.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - lefthook
  - unrs-resolver

overrides:
  serialize-javascript@<7.0.5: '>=7.0.5'

strictDepBuilds: true
