minimumReleaseAge: 7200

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - lefthook
  - unrs-resolver

strictDepBuilds: true
minimumReleaseAgeExclude:
  # Renovate security update: h3@1.15.5
  - h3@1.15.5
