import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { css } from '@emotion/react'
import {} from '@/components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src="https://gravatar.com/avatar/8fd43c0ce852b1dacd0ad04c458040b1?s=120"
        alt="Icon"
        width={120}
        height={120}
      />
    </>
  )
}

export default Home
