# Pull Request

name: PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  # Semantic PR Title
  semantic:
    name: Semantic PR Title
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    timeout-minutes: 10

    if: github.repository == 'Hiratake/hiratake-web'

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@00282d63cda40a6eaf3e9d0cbb1ac4384de896e8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
